### PR TITLE
ENH: Add julia language support

### PR DESCRIPTION
**Pull request by sglyon**

### CODE REVIEW

**Comment by leipert** [comment]
Thanks for your pull request. Unfortuantely the fenced code blocks in language-pfm are generated.

Why is there a `include: 'source.css.less'` inside the julia blocks? I cannot find them in language-gfm julia blocks: https://github.com/atom/language-gfm/blob/master/grammars/gfm.cson#L609-L624

**Comment by sglyon** [comment]
I actually have no idea why that is there. I just copied the [python and swift](https://github.com/leipert/language-pfm/blob/dist/grammars/pfm.cson#L1190-L1222) definitions and hoped you had a good reason to include that ;)

They totally don't belong.

Can you tell me how these are generated? I'm happy to add Julia to that list.

**Comment by leipert** [comment]
Actually it is a bit hacky. But have a look in the master branch:
https://github.com/leipert/language-pfm/blob/master/src/languages.js

**Comment by leipert** [comment]
Does julia work for you in the language-gfm package?

**Comment by sglyon** [comment]
Yep it works there.

looks like [this line](https://github.com/leipert/language-pfm/blob/master/src/languages.js#L106) is what puts less in all of these blocks

**Comment by leipert** [comment]
ah i know why that is

in pandoc you can write some stuff like classes into the fenced code blocks

``````
```{.julia startNumber="100"} <- this is going to be styled with css styles

```
``````

**Comment by sglyon** [comment]
Nice. Yeah that makes sense. Want me to move the julia portion to be generated from `src/languages.js`?

**Comment by leipert** [comment]
nope, will do it now myself right now. There are some more languages that need to be added. Once I pushed you can confirm that it works ;)

**Comment by sglyon** [comment]
That's easy :+1:

**Comment by leipert** [comment]
Does it work, @spencerlyon2?

**Comment by sglyon** [comment]
Yup, works. Thanks!

**Comment by leipert** [comment]
Thanks for your PR, have fun using language-pfm ;)

**Comment by sglyon** [comment]
Will do, thanks for the quick iterations on this.

**Pull request closed without merging**
